name: Build

on: [push, workflow_dispatch]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        uses: gradle/gradle-build-action@v2.5.1
        with:
          arguments: build
          gradle-version: wrapper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}