name: Release to Maven Central

on:
  workflow_dispatch:
    inputs:
      increment:
        type: choice
        description: Increment
        required: true
        options:
          - Patch
          - Minor
          - Major

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Stage on Maven Central
        uses: gradle/gradle-build-action@v2
        with:
          arguments: > 
            publishAllPublicationsToOSSRHRepository
            -Dsigning.keyId=${{ secrets.SIGNING_KEY }}
            -Dsigning.password=${{ secrets.SIGNING_PASSWORD }}
            -DossrhUsername=${{ secrets.OSSRH_USERNAME }}
            -DossrhPassword=${{ secrets.OSSRH_PASSWORD }}
          gradle-version: wrapper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}